import "./project.css";
import marie2 from "../assets/marie2.jpg";
import mariesystem from "../assets/mariesystem.png";
import tgs from "../assets/tgs.png";
import model from "../assets/model.gif";
import marieuserstudy from "../assets/marieuserstudy.png";
import Footer from "../components/footer/Footer";


const Marie = () => {
  return (
    <>
        
        <nav className='nav container'>
            <a href='/' className='nav__logo'>MS Design
            </a>
        </nav>
        
        <div className="container"> 
            <div className="project__container">
                <div className="project__title">Multimodal Activity Recognition in Industrial Environment</div>
                <div className="project__role">Lead UX Designer | Researcher</div>
            </div>

            <div class="project__fullimg" alt="marie">
                <img src={marie2} alt="AI in manufacutring cover"/>
            </div>

            <h2 className="project__section-title">How to Fine-tune Multimodal and LLM for Specific Domain</h2>
            <div className="project__text">The adoption of AI approaches is increasing across domains. Beside common language questions. How can we use multiple AI models including large language models? we want to use manufacturing process as an example to explore the answers.</div>

            <div class="project__fullimg" alt="marie">
                <img src={mariesystem} alt="marie system"/>Marie sensing system
            </div>

            <div className="project__text">We collected dataset across different process line among different countries, to study how technicians are working, and created MARIE system to do performance support for them.</div>

            <div className="project__section-title">Due to confidential requirement, I only show my published work here, explainable subsystem of MARIE: TGS. If interested, contact me to learn more about MARIE. </div>


            <h2 className="project__section-title">Task Guidance System</h2>
            <div className="project__text">Task Guidance System, TGS, is designed to facilitate collaboration between domain experts and AI researchers in fine-tuning the various components of the multi-modal AI system.</div>
            <div className="project__text">Visualization of each individual models performance, e.g., uncertainty
                score, importance score and inconsistent outcome to enable appropriate user feedback.</div>

            <div class="project__fullimg" alt="marie">
                <img src={tgs} alt="task guidance system"/>Some details of the image are blurred for confidential reason
            </div>

            <div className="project__text">
            TGS visualizes multiple models used by the multi-modal AI supporting system for Action Recognition, MSTCN; Automatic Speech Recognition, Whisper; Intent Recognition, BERT, etc. which infer the user actions and
            predict their next steps. 
            </div>

            <div className="project__text">
            TGS can help domain experts understand the AI models. With TGS, the
            domain experts can see how their inputs are taken by the models and com
            pare predictions generated by each model to the phenomenon the predictions
            represent. This is possible because TGS visualizes how each model analyzes its
            inputs and presents the output of each model. 
            </div>

            <div class="project__fullimg" alt="marie">
                <img src={model} alt="explain model output"/>Why the AI agent ask me this question?
            </div>

            <div className="project__text">
            In addition, TGS allows domain
            experts with ground-truth knowledge to critique these predictions through its
            dialogue system and, thereby, lets AI researchers fine-tune the AI models.
            </div>

            <h2 className="project__section-title">How do domain expert and AI researcher think about this explainable AI Interface?</h2>
            <div class="project__fullimg" alt="marie">
                <img src={marieuserstudy} alt="users feedback"/>
            </div>
            <div className="project__text">
            AI researchers report that aligned multimodal data are valuable to be streamed together.
            </div>
            <div className="project__text">
            Domain experts demonstrated a willingness to help AI researchers using TGS,
            and identified novel challenges AI researchers might face in negotiating a space
            of multiple or changing approaches in methods or objects.
            </div>


            <div className="project__text">
                More can be found in paper: 
                <i class = "bx bx-award"></i>
                <a href="https://ceur-ws.org/Vol-3554/paper20.pdf">An Explainable AI User Interface for Facilitating
                    Collaboration between Domain Experts and AI Researchers</a>
            </div>


        </div>

        <Footer/>
    </>
  )
}

export default Marie